### ISSUE TITLE
Cleanup by default

### ISSUE THREAD

**Issue by mrocklin** [jacobtomlinson/dask-cloud#5]
In the docs you mention that if the launching process cleans up properly then everything should be collected on the ECS side, resulting in no unexpected charges.

Based on your previous request for an `--idle-timeout` keyword, my guess is that you plan to add inactivity timeouts to all resources created by this system by default to more robustly clean things up.  Was this your plan?

**Comment by jacobtomlinson** [comment]
Yeah this is the case [here](https://github.com/jacobtomlinson/dask-cloud/blob/36502620ab7f93bb1279192b973881eba50ce088/dask_cloud/providers/aws/ecs.py#L908).

The scheduler will exit after a default idle timeout. Workers will exit after the scheduler is lost for a default timeout. Logs will be purges after a default of 30 days. These are all the chargeable resources that are created.

So if a connection is cut and the cluster idles everything chargeable will be removed automatically. However there will be some shrapnel left over that will get cleaned up next time someone creates a cluster.
